name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.user
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/cicd-week-18:latest
            ${{ secrets.DOCKER_USERNAME }}/cicd-week-18:${{ github.sha }}

      # Verify pushed image
      - name: Verify image on Docker Hub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-week-18:latest
          docker images ${{ secrets.DOCKER_USERNAME }}/cicd-week-18
    
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
         host: ${{ secrets.EC2_HOST }}
         username: ${{ secrets.EC2_USERNAME }}
         key: ${{ secrets.EC2_SSH_KEY }}
         script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-week-18:latest
            sudo docker stop mynextappcicd || true
            sudo docker rm mynextappcicd || true
            sudo docker run -d -p 3005:3000 --name mynextappcicd ${{ secrets.DOCKER_USERNAME }}/cicd-week-18:latest